name: Zip and Attach to Release
on:
  release:
    types: [created]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Create ZIP
        run: |
          zip -r ${REPO_NAME}-${VERSION}.zip . -x "*.git*"

      - name: Upload ZIP to Release (GH CLI)
        run: |
          echo "Uploading ${REPO_NAME}-${VERSION}.zip"
          ls -la
          gh release upload $VERSION ${REPO_NAME}-${VERSION}.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}