name: Zip and Attach to Release
on:
  release:
    types: [created]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Create ZIP
        run: |
          zip -r ${REPO_NAME}-${VERSION}.zip . -x "*.git*"

      - name: Upload ZIP to Release (GH CLI)
        run: |
          echo "Uploading ${REPO_NAME}-${VERSION}.zip"
          ls -la
          gh release upload $VERSION ${REPO_NAME}-${VERSION}.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
      - name: Upload to S3
        run: |
          aws s3 cp ${REPO_NAME}-${VERSION}.zip s3://stage-cfe-users/${REPO_NAME}/${VERSION}/

      